[package]
name = "hermes"
version = "0.1.0"
authors = ["Hao Shi <shisoftgenius@gmail.com>"]
edition = "2018"

[lib]
name = "hermes"

[dependencies]
parking_lot = "*"
log = "*"

[dev-dependencies]
simple_logger = "1"